services:
  bot:
    build: .
    image: ghcr.io/yesmohsen/telegram-api-generator-bot:latest
    container_name: telegram-api-bot
    restart: unless-stopped
    volumes:
      - config_data:/app/data

volumes:
  config_data:
