services:
  bot:
    build: .
    image: ghcr.io/yesmohsen/telegram-api-generator-bot:latest
    container_name: telegram-api-bot
    restart: on-failure
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - config_data:/app/data

volumes:
  config_data:
