services:
  bot:
    build: .
    image: ghcr.io/yesmohsen/telegram-api-generator-bot:latest
    container_name: telegram-api-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
